describe('empty spec', () => {
  it('passes', () => {
    cy.viewport(1280, 720)
    cy.visit('https://www.freepik.com')
    cy.get('#search-value-fake').type("background")
    cy.wait(1000)
    cy.get('.button--lg > .icon--search').click()
    cy.get('details[data-key="people"] > :nth-child(1)').click()
    cy.get('[for="filter-ethnicity-indian"] > :nth-child(2)').click()
    cy.get('[for="filter-range-number2"] > :nth-child(2)').click()
    cy.get('.pagination__input > input').clear()
    cy.get('.pagination__input > input').type("36")
    cy.get('#onetrust-accept-btn-handler').click()
    cy.wait(1000)
    cy.scrollTo(0, 5200)
    cy.get('a[data-id="11543827"').click()
    cy.get('#download-wrapper-button').should("be.enabled")
    cy.get('.detail').contains("11543827")
  })
})